################################################################################
# Minimal Judge0 config for local development
#
# Used by: docker/judge0.docker-compose.yml
# Docs: https://github.com/judge0/judge0/blob/master/judge0.conf
################################################################################

# Redis
REDIS_HOST=redis
REDIS_PASSWORD=judge0_redis_password

# Postgres
POSTGRES_HOST=db
POSTGRES_DB=judge0
POSTGRES_USER=judge0
POSTGRES_PASSWORD=judge0_postgres_password

# Allow waiting for synchronous result if requested
ENABLE_WAIT_RESULT=true

